name: Creates and Updates PR

on:
  push:
    branches:
      - dev

jobs:
  prod-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create-description
        run: sh ${GITHUB_WORKSPACE}/.github/simple_changelog.sh
        id: changelog
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "master"
          pr_title: "Deploy Prod"
          pr_label: "Production Deploy"
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: update-pull-request
        uses: kt3k/update-pr-description@v1.0.1
        with:
          pr_body: ${{ steps.description.outputs.changelog }}
          destination_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
