name: Create Deploy Prod PR

on:
  push:
    branches:
      - "dev"

jobs:
  create-prod-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prod-pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "master"
          pr_title: "Deploy Prod"
          pr_body: |
            <!-- START pr-commits -->
            <!-- END pr-commits -->
          pr_label: "Production Deploy"
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
