name: Update Deploy Prod PR body

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  prod-pull-request:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - uses: actions/checkout@v2
      - name: Pull Request Body
        uses: technote-space/pr-commit-body-action@v1
